name:                eviefp-blog
version:             0.1.0.0
github:              "eviefp/eviefp.github.io"
license:             BSD3
author:              "Evie Ciobanu"
maintainer:          "blog@eevie.ro"
copyright:           "2022 Evie Ciobanu"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Blog built with slick!
category:            Slick-Site

description: Evie's technical blog

executables:
  build-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >= 4.7 && < 5
    - shake
    - slick
    - text
    - containers
    - unordered-containers
    - lens
    - aeson
    - lens-aeson
    - time
